GET http://localhost:3000/api/v1/products
// Headers:
###
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
    "email": "ben@gmail.com",
    "password": "test12378"

}
###
POST http://localhost:3000/api/v1/auth/sign-
Content-Type: application/json

{
    "name": "alain",
    "email": "alain@gmail.com",
    "password": "test123789"

}
###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "name": "test",
    "price": 100,
    "description": "test",
    "image": "test",
    "category": "test",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDU5NTMyMjUsImV4cCI6MTc0NjAzOTYyNX0.gQplhgH50VqkbTREhnQdZORG1MWbVv_yO9LEp9oY8HI",
}
### 
GET http://localhost:3000/api/v1/users
###
DELETE  http://localhost:3000/api/v1/users/681139e500d965272038bd11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTEzOWU1MDBkOTY1MjcyMDM4YmQxMSIsImlhdCI6MTc0NTk2MjQ4MSwiZXhwIjoxNzQ2MDQ4ODgxfQ.5bIEBecQAxVWAJUFDLPvCtSGqZEN0bkpR18wW81eN0k`
###
DELETE http://localhost:3000/api/v1/users/64a2f3b4c9d3e5f8b8e4a2c1?

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDU5NTkzOTgsImV4cCI6MTc0NjA0NTc5OH0.9TJ3yqMRRVOW99iWOMxJCGRZZbcCpC479oTfcBNocEo
###
GET http://localhost:3000/api/v1/users